### ISSUE TITLE
Skill points not given back after go to Main and NPC Guide don't reset skill points

### ISSUE THREAD

**Issue by dniloms** [GustavoContreiras/TheForgottenTibia#11]
Ao garantir nivel 8 e passar o personagem para Main Land, as skills são resetadas, porém os pontos  de skill para redistribuir não voltam ao personagem, ficam 0.

A mesma coisa para o npc Guide na função de resetar skills.

**Comment by GustavoContreiras** [comment]
Isso acontece porque eu refiz o sistema de pontos inteiro. Tirei ele dos scripts .lua e coloquei nas sources .cpp.

A parte dos skills points voltar ao personagem no nível 8 é fácil resolver.

A parte do NPC Guide acho que é mais complexa.

Atualmente não estou mais trabalhando no projeto (estou muito ocupado com outro), infelizmente, então não poderei ajudar.

Basicamente, a função de resetar pontos não é mais uma função lua, e sim uma função c++ dentro das sources que deve ser chamada através de uma função lua.

--

This happens because I remade the skill points system. To solve that, NPC Guide and NPC Oracle should call the new reset skill points function that is available on c++ sources.

**Comment by dniloms** [comment]
Vixe, eu não sei programar, eu tô acompanhando seu projeto pra poder jogar com alguns amigos um dia hehe. Esse sistema de distribuir pontos me lembra muito dark souls. é incrível!!

Fico na torcida para que volte volte com o projeto quando tiver tempo. Até lá vou dando meus pulos, testando e aprendendo kkk. força

**Comment by GustavoContreiras** [comment]
Fix with commit https://github.com/GustavoContreiras/TheForgottenTibia/commit/bdccefef0c03d49aa6b8ed3a419d8f06f3789f2b
